### ISSUE TITLE
Sending files using urls always fails 

### ISSUE THREAD

**Issue by jmy2022** [mr-linch/go-tg#113]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x10481a3fc]

**Comment by mr-linch** [comment]
Hey @jmy2022! 

Could you provide a reproducible example? 

UPD: reproduced, will correct soon

**Comment by mr-linch** [comment]
@jmy2022 issue is resolved and will be released in [v0.7.0](https://github.com/mr-linch/go-tg/releases/tag/v0.7.0), thank you for your report, and you are welcome to reopen the issue if you have any troubles related to that scope.

**Comment by jmy2022** [comment]
thanks，Your design works so well that I set it up in google cloud run
